[package]
name = "calculator"
version = "0.1.0"
authors = ["Miguel Bartelsman <mbartelsmanm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = ""
assert_matches = ""
